### ISSUE TITLE
Question about “matched key count”

### ISSUE THREAD

**Issue by TeRe20200** [corona-warn-app/cwa-app-ios#1268]
On the 6th the Coronaapp pushed me two exposures with low risk. Those two „keys“ can be found on my exposure check login from that day. 
![B248A632-D00C-45A1-BA69-40018C791028](https://user-images.githubusercontent.com/67905190/92658761-65623400-f2f7-11ea-8917-68bb2095a2d5.png)

The two exposures with low risk are still shown on my coronaapp up until now 
![BF12A715-334D-4C9B-87EE-3B8E157229F3](https://user-images.githubusercontent.com/67905190/92658827-84f95c80-f2f7-11ea-86d4-650c25117dfa.png)
but they cannot be found on the logs from the 7th, 8th and today 
![32370EC6-D1ED-49FD-BDCC-14F4FFFC1919](https://user-images.githubusercontent.com/67905190/92658924-aeb28380-f2f7-11ea-8f7d-b6c62cb8b80b.jpeg)
![2969940C-0783-45A4-8426-2B80BF51BC1C](https://user-images.githubusercontent.com/67905190/92658932-b2dea100-f2f7-11ea-994f-43cd4ff3a518.jpeg)
![1C106564-98C8-4C4F-9AF7-05748476978C](https://user-images.githubusercontent.com/67905190/92658933-b4a86480-f2f7-11ea-9419-db89c599e33a.jpeg)

Can someone please explain me why?
**Thank you so much**

---
Internal Tracking ID: EXPOSUREAPP-2960

**Comment by GPclips** [comment]
Hello @TeRe20200,

I have created a Jira issue and forwarded your case to our development team.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by daimpi** [comment]
@GPclips a small OT suggestion:

What do you think of the idea to make a small comment in an issue before moving it into another repo? The reason why I bring this up is that subscriptions seem to get lost in this process and ppl who previously subscribed will not be notified of any future updates while the move itself also seemingly doesn't show up in ones notifications. 

Lemme know what you think 🙂.

**Comment by FelixKuehl** [comment]
I am experiencing the same Issue under IOS 14. I am getting "one exposure with low risk" but can not find a single match in my exposure logs. I kind of remember, that we had a similar issue here before about exposures that were once counted but not erased after 14 days?

I am attaching my exposure log.

![image](https://user-images.githubusercontent.com/13168478/95061678-34113400-06fc-11eb-83b0-532ce3d9e8d6.png)

```
{
  "Build" : "18A393",
  "ExportVersion" : 2,
  "ExposureChecks" : [
    {
      "Timestamp" : "2020-10-03 22:14:48 +0200",
      "Files" : [
        {
          "Hash" : "3704C100F8086E1CBA059A984D6E25DBFE149229D9EC3F0F4871B25889F97BF8",
          "MatchCount" : 0,
          "KeyCount" : 16008,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:49 +0200"
        },
        {
          "Hash" : "BE5A4D6C22D23A58BBC82A4C070FCBF1C0EC3B38CEA7923EBD4BE82FFC6734AB",
          "MatchCount" : 0,
          "KeyCount" : 14299,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "99D35FBF030B71528DAA0BEAE55265B6A88821708B5C2A6FFABFE294F792C0EA",
          "MatchCount" : 0,
          "KeyCount" : 12850,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "83164C315E94C84C4F80381F64B10532DEC9B7454BD1AF4D8E8E71B0EADDB77A",
          "MatchCount" : 0,
          "KeyCount" : 12700,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "5482C7DF9369314891E75675D461B5FC5BA2B20A29C2F61C7A143C69F304AF4B",
          "MatchCount" : 0,
          "KeyCount" : 8430,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "0CDC66BAB3C15F790E2BCF86794B496F328C1819A998E8302CC6BBC55209821F",
          "MatchCount" : 0,
          "KeyCount" : 6071,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "EE961B7259874A14523641AF037F5D78AED922EEABD5AACBF443708EEE7D1B27",
          "MatchCount" : 0,
          "KeyCount" : 9593,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-03 22:14:48 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-10-02 07:42:56 +0200",
      "Files" : [
        {
          "Hash" : "BE5A4D6C22D23A58BBC82A4C070FCBF1C0EC3B38CEA7923EBD4BE82FFC6734AB",
          "MatchCount" : 0,
          "KeyCount" : 14299,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:57 +0200"
        },
        {
          "Hash" : "99D35FBF030B71528DAA0BEAE55265B6A88821708B5C2A6FFABFE294F792C0EA",
          "MatchCount" : 0,
          "KeyCount" : 12850,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "83164C315E94C84C4F80381F64B10532DEC9B7454BD1AF4D8E8E71B0EADDB77A",
          "MatchCount" : 0,
          "KeyCount" : 12700,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "5482C7DF9369314891E75675D461B5FC5BA2B20A29C2F61C7A143C69F304AF4B",
          "MatchCount" : 0,
          "KeyCount" : 8430,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "0CDC66BAB3C15F790E2BCF86794B496F328C1819A998E8302CC6BBC55209821F",
          "MatchCount" : 0,
          "KeyCount" : 6071,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "EE961B7259874A14523641AF037F5D78AED922EEABD5AACBF443708EEE7D1B27",
          "MatchCount" : 0,
          "KeyCount" : 9593,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-02 07:42:56 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-30 23:53:05 +0200",
      "Files" : [
        {
          "Hash" : "83164C315E94C84C4F80381F64B10532DEC9B7454BD1AF4D8E8E71B0EADDB77A",
          "MatchCount" : 0,
          "KeyCount" : 12700,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "5482C7DF9369314891E75675D461B5FC5BA2B20A29C2F61C7A143C69F304AF4B",
          "MatchCount" : 0,
          "KeyCount" : 8430,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "0CDC66BAB3C15F790E2BCF86794B496F328C1819A998E8302CC6BBC55209821F",
          "MatchCount" : 0,
          "KeyCount" : 6071,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "EE961B7259874A14523641AF037F5D78AED922EEABD5AACBF443708EEE7D1B27",
          "MatchCount" : 0,
          "KeyCount" : 9593,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-30 23:53:06 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-29 23:31:46 +0200",
      "Files" : [
        {
          "Hash" : "5482C7DF9369314891E75675D461B5FC5BA2B20A29C2F61C7A143C69F304AF4B",
          "MatchCount" : 0,
          "KeyCount" : 8430,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "0CDC66BAB3C15F790E2BCF86794B496F328C1819A998E8302CC6BBC55209821F",
          "MatchCount" : 0,
          "KeyCount" : 6071,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "EE961B7259874A14523641AF037F5D78AED922EEABD5AACBF443708EEE7D1B27",
          "MatchCount" : 0,
          "KeyCount" : 9593,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-29 23:31:46 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-29 00:35:31 +0200",
      "Files" : [

      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-27 12:00:43 +0200",
      "Files" : [
        {
          "Hash" : "EE961B7259874A14523641AF037F5D78AED922EEABD5AACBF443708EEE7D1B27",
          "MatchCount" : 0,
          "KeyCount" : 9593,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:44 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-27 12:00:43 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-26 08:48:29 +0200",
      "Files" : [
        {
          "Hash" : "D3773CBA4F74C9D60CB242406AFACE951AF6F0C390C917A727B23B2D9812ACBE",
          "MatchCount" : 0,
          "KeyCount" : 12457,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-26 08:48:29 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-25 03:49:41 +0200",
      "Files" : [
        {
          "Hash" : "7A04AF10A6A702F04FE81A34FB4B14973F87DF8AF1D9F7009BB68042696880E6",
          "MatchCount" : 0,
          "KeyCount" : 12229,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        },
        {
          "Hash" : "A7FC2C16D1FC1F1557B3AC53602570338D182E14EF1D0C8EC3681C0FC061B938",
          "MatchCount" : 0,
          "KeyCount" : 7762,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-25 03:49:42 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-24 03:07:15 +0200",
      "Files" : [
        {
          "Hash" : "1DD7BF61DA5DC000C016D98EE5CDC1A4FC9A33B139BDA82DC2E31BA239ACF5E5",
          "MatchCount" : 0,
          "KeyCount" : 13539,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:16 +0200"
        },
        {
          "Hash" : "B13EEA34F07AE2FCB1855CE111C57A585FC9559C3ABC678573D5AB9049D31360",
          "MatchCount" : 0,
          "KeyCount" : 9405,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "A7FC2C16D1FC1F1557B3AC53602570338D182E14EF1D0C8EC3681C0FC061B938",
          "MatchCount" : 0,
          "KeyCount" : 7762,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        },
        {
          "Hash" : "96D33FB8690267879080BA3427249995F4D3802D61A3F8AC7FA74A971619F6C6",
          "MatchCount" : 0,
          "KeyCount" : 7395,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-24 03:07:15 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-22 23:15:42 +0200",
      "Files" : [
        {
          "Hash" : "9341DB097412B04CA7C63D58427C60309D154C9A28521876813540BF75A94A9E",
          "MatchCount" : 0,
          "KeyCount" : 8390,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:43 +0200"
        },
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:43 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:43 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:43 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:43 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "A7FC2C16D1FC1F1557B3AC53602570338D182E14EF1D0C8EC3681C0FC061B938",
          "MatchCount" : 0,
          "KeyCount" : 7762,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "96D33FB8690267879080BA3427249995F4D3802D61A3F8AC7FA74A971619F6C6",
          "MatchCount" : 0,
          "KeyCount" : 7395,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "EEE00D6496F3C415EDE42B67863CD68EDF5C9A37F96AA881B8BC0C4C3F9C8EAB",
          "MatchCount" : 0,
          "KeyCount" : 6885,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        },
        {
          "Hash" : "1843FEBCC2BE3F085F3EDC4CA3602E5DFFE52BAA8EDBDB37AFFF0C83D62F876E",
          "MatchCount" : 0,
          "KeyCount" : 4932,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-22 23:15:42 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-21 09:16:01 +0200",
      "Files" : [
        {
          "Hash" : "E82F612E82528B76C006F0A0FE0806937839E1EF5B1CB91AA699A8DC8BBE9C70",
          "MatchCount" : 0,
          "KeyCount" : 3250,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:02 +0200"
        },
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:02 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:02 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "A7FC2C16D1FC1F1557B3AC53602570338D182E14EF1D0C8EC3681C0FC061B938",
          "MatchCount" : 0,
          "KeyCount" : 7762,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "96D33FB8690267879080BA3427249995F4D3802D61A3F8AC7FA74A971619F6C6",
          "MatchCount" : 0,
          "KeyCount" : 7395,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "EEE00D6496F3C415EDE42B67863CD68EDF5C9A37F96AA881B8BC0C4C3F9C8EAB",
          "MatchCount" : 0,
          "KeyCount" : 6885,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "1843FEBCC2BE3F085F3EDC4CA3602E5DFFE52BAA8EDBDB37AFFF0C83D62F876E",
          "MatchCount" : 0,
          "KeyCount" : 4932,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        },
        {
          "Hash" : "70ECDF30772933C26E8B6F572E416433C271DE19466932DB79875A3C0754AC7E",
          "MatchCount" : 0,
          "KeyCount" : 4630,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-21 09:16:01 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    },
    {
      "Timestamp" : "2020-09-20 07:53:53 +0200",
      "Files" : [
        {
          "Hash" : "C586B7800DAC12FC54F8E9A3B4B27CB1086BCE296249B39567D8953A7089655B",
          "MatchCount" : 0,
          "KeyCount" : 5290,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "AD521A27B2EDAAFD5BFDC719D59599C223425EB8ED8A9775AD9D4DE3F8EF7BD9",
          "MatchCount" : 0,
          "KeyCount" : 10369,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "905748FDDC3B77A4F0C3DA3C8FFB4135FECAC18A95450D7DA269F5FD5E1852BD",
          "MatchCount" : 0,
          "KeyCount" : 11165,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "F64A7E5BEB59B8AD0BF5C80EF95D994F403D25D5A4EF95A9FB485D53EBCA484D",
          "MatchCount" : 0,
          "KeyCount" : 10235,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "D07F64B0D04AB1F5D03C32092E19307A9638489CDB3A53CAF61EBDA11FA956F6",
          "MatchCount" : 0,
          "KeyCount" : 9548,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "967C468EC5F587BD72E84365A680B1805959C4DF092530F504917915BA429895",
          "MatchCount" : 0,
          "KeyCount" : 5655,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "C024D384983CAE9950A84776B5AF5D42441E16314606E8FCBCE68EC852C562CE",
          "MatchCount" : 0,
          "KeyCount" : 4977,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "50D00BE00C3989D5F3753241FEDC873B2090273426914A495B118553DF790774",
          "MatchCount" : 0,
          "KeyCount" : 5310,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "A7FC2C16D1FC1F1557B3AC53602570338D182E14EF1D0C8EC3681C0FC061B938",
          "MatchCount" : 0,
          "KeyCount" : 7762,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "96D33FB8690267879080BA3427249995F4D3802D61A3F8AC7FA74A971619F6C6",
          "MatchCount" : 0,
          "KeyCount" : 7395,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "EEE00D6496F3C415EDE42B67863CD68EDF5C9A37F96AA881B8BC0C4C3F9C8EAB",
          "MatchCount" : 0,
          "KeyCount" : 6885,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "1843FEBCC2BE3F085F3EDC4CA3602E5DFFE52BAA8EDBDB37AFFF0C83D62F876E",
          "MatchCount" : 0,
          "KeyCount" : 4932,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "70ECDF30772933C26E8B6F572E416433C271DE19466932DB79875A3C0754AC7E",
          "MatchCount" : 0,
          "KeyCount" : 4630,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        },
        {
          "Hash" : "6E6F1272436AB993420ACD7EBF6A2F018329F44B79115D1DD6BB0F0604DF8AA4",
          "MatchCount" : 0,
          "KeyCount" : 2158,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-09-20 07:53:53 +0200"
        }
      ],
      "AppBundleIdentifier" : "de.rki.coronawarnapp"
    }
  ],
  "DeviceProductType" : "iPhone12,5"
}
```

**Comment by svengabr** [comment]
Hello everyone and thanks for your feedback.

The bug you experienced will most likely be fixed with iOS 14.2 Public Beta 2 according to this comment:
https://github.com/corona-warn-app/cwa-app-ios/issues/1106#issuecomment-703174855

The developers have also marked the attached Jira ticket for this issue as obsolete since its a duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1106

To keep the board clean, I need to close this issue and kindly ask you to move your conversation to the above-mentioned issue.

Thank you for your support and understanding!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by daimpi** [comment]
@FelixKuehl 
> I kind of remember, that we had a similar issue here before about exposures that were once counted but not erased after 14 days?

Just to answer this specific question: Yes, this was an [Android exclusive problem](https://github.com/corona-warn-app/cwa-app-android/issues/911) and it worked slightly different: There you had matches initially showing up in CWA & EN log, but even when phased out of the log they persisted in CWA. This issue has since been fixed with the release of CWA 1.3 though.

**Comment by TeRe20200** [comment]
I know this issue is closed, but I still have the same problem. App shows one encounter, logs show zero. Can someone tell me why?

**Comment by Ein-Tim** [comment]
@TeRe20200 
If you are using iOS, please update to iOS 14.1 and this Issue will be solved (see: https://github.com/corona-warn-app/cwa-app-ios/issues/1106)

**Comment by TeRe20200** [comment]
Hello Ein-Tim, thank you for your very quick response. But I have iOS 14.1 and still my App shows me one Risikobegegnung 
![0C66FD33-FA34-460D-BB24-EAAC69062484](https://user-images.githubusercontent.com/67905190/96874837-dbb99080-1476-11eb-908a-9ba40b55a6bf.jpeg)
but it cannot be found when it comes to my Exposure checks. Am I too stupid, or? 

https://www.file-upload.net/download-14331293/ExposureChecks-2020-10-22.json.html

**Comment by daimpi** [comment]
@TeRe20200 did your CWA perform an update/sync since you upgraded to iOS 14.1? If not you'll have to wait until the next update/sync happens, to see the fix in action.

**Comment by TeRe20200** [comment]
@Ein-Tim @daimpi Thank you smart people!
