### ISSUE TITLE
QR code not sanitized because of all caps.

### ISSUE THREAD

**Issue by trispo** [corona-warn-app/cwa-app-ios#1438]
## Describe the bug

I had a test yesterday and got a sheet with the QR code for the CWA. I tried to scan it but the app always says "Befund wurde nicht gefunden". First I thought this means, the test is not yet reported to any laboratory but as this scan failure still exists I decided to look into the source code.

The QR code I got is in all caps like this: `HTTPS://LOCALHOST/?######-########-####-####-####-############`

The method `sanitizeAndExtractGuid` in `ExposureSubmissionOverviewViewModel` does not sanitize this code because it searches for a String starting with lowercase letters for the URL scheme and host.
`^https:\\/\\/localhost\\/\\?(?<GUID>[0-9A-Fa-f]{6}-[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12})$`.
This means, my QR code will not be scanned. 

## Expected behaviour

The method `sanitizeAndExtractGuid` accepts QR codes with all caps as there is software in the wild which produces all caps QR codes.

## Technical details

- iOS Version: iOS 14.2 GM
- Device: iPhone XS

## Possible Fix

`sanitizeAndExtractGuid` should convert the input string to lowercase before trying to match with the regex.

EXPOSUREAPP-3546

**Comment by thomasaugsten** [comment]
We already reworked this for v1.6
https://github.com/corona-warn-app/cwa-app-ios/blob/release/1.6.x/src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift

**Comment by trispo** [comment]
The provided change is not sufficient to solve the problem I described above.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1045441/97779641-9a646780-1b7f-11eb-8887-4017c61b55c1.png">

[ENA.playground.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5469082/ENA.playground.zip)

**Comment by thomasaugsten** [comment]
Thats unfortunate that URLComponent is case sensitive and some QR codes are not following the guide line.
We will fix this as soon as possible. Thanks for pointing this out and your investigation here.

**Comment by thomasaugsten** [comment]
@trispo Can you please provide me via e-mail where you get this QR-Code and also do some investigation whats the responsible test lab?
thomas.augsten@sap.com

**Comment by trispo** [comment]
Done

**Comment by heinezen** [comment]
This issue was fixed in CWA version 1.6, so I'll close this.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@heinezen as per [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/1438#issuecomment-719957197) the issue was not completely fixed in 1.6 - could you please clarify and consider to reopen?
Thanks

**Comment by heinezen** [comment]
@ndegendogo It was fixed in 3767c69c69b95fade3f078ffc7fb09e5668ed2f6 of https://github.com/corona-warn-app/cwa-app-ios/pull/1446 which was included in 1.6. The scheme and host is now lowercased. It was also successfully tested internally for Android and iOS. 

Or am I missing something?

**Comment by ndegendogo** [comment]
@heinezen sorry, yes, you are right.
The comments I saw were pre-release 1.6.
And I see even a unit test implemented for exactly the pattern reported 👍
