### ISSUE TITLE
[RAT-Profile] Top gets blurred in white/black, when going back from your consent

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2685]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [possible] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: 14.5.1
- App version: 2.2.1 (0)

## Describe the bug

https://user-images.githubusercontent.com/73582096/117951672-aee6a100-b314-11eb-9589-dcf5281b62d7.MOV

## Steps to reproduce the issue

Watch the video

## Question
Should I upload an error report?

---
Internal Tracking ID: [EXPOSUREAPP-7225](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7225)

**Comment by dsarkar** [comment]
@jucktnich Thanks for the report. No error report for the moment needed. 


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2687

**Comment by Ein-Tim** [comment]
This has been fixed in version 2.3 which has been released to the App Store yesterday @jucktnich.

**Comment by Ein-Tim** [comment]
@jucktnich Could you confirm the fix and close this issue, please?

**Comment by jucktnich** [comment]
Yes, but if change to light mode in the your consent screen, the back button still appears white.

**Comment by larswmh** [comment]
> Yes, but if change to light mode in the your consent screen, the back button still appears white.

This is actually still reproducible. I'll forward this internally. 

https://user-images.githubusercontent.com/88365935/221183779-82514fe9-2fd1-4e3e-893f-6f917fcb384d.mov

---
Internal Tracking ID: [EXPOSUREAPP-14865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14865)

**Comment by Ein-Tim** [comment]
- PR fixing this https://github.com/corona-warn-app/cwa-app-ios/pull/5072

**Comment by Ein-Tim** [comment]
@brianebeling The `Fix 3.2` label can be added to this issue.
